# This GHA Workflow to run SonarQube Scanner for PHP code
name: SonarQube Scanner

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

on:
  pull_request:
    types: [opened, reopened]

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone this repo
      id  : git
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: SonarQube Scanner
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: ./
